FilmsCatalog/Models/Film.cs
namespace FilmsCatalog.Models
{
    public class Film
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Year { get; set; }
        public string Director { get; set; }
        public User User { get; set; }
        public string FilePath { get; set; }

    }
}

FilmsCatalog/ViewModels/FilmViewModel.cs
using FilmsCatalog.Models;

namespace FilmsCatalog.ViewModels
{
    public class FilmViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public int Year { get; set; }
        public string Director { get; set; }
        public string Description { get; set; }
        public string FilePath { get; set; }
        public User User { get; set; }
        
    }

    public class FilmShortViewModel
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string FilePath { get; set; }
        public User User { get; set; }
    }
}

FilmsCatalog/Controllers/FilmsController.cs
using FilmsCatalog.Services;
using FilmsCatalog.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Threading.Tasks;

namespace FilmsCatalog.Controllers
{
    public class FilmsController : Controller
    {
        private readonly IFilmsService _filmsService;
        public FilmsController(IFilmsService filmsService)
        {
            _filmsService = filmsService;
        }

        
        [HttpGet]
        [Authorize] 
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(CreateFilmViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _filmsService.Create(model, User);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [HttpGet]
        [Route("{id}")]
        public async Task<IActionResult> Details(int id)
        {
            try
            {
                var film = await _filmsService.GetFilm(id);
                return View(film);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }

        [HttpGet]
        [Authorize]
        [Route("edit/{id}")]
        public async Task<IActionResult> Edit(int id)
        {
            try
            {
                var film = await _filmsService.GetForEdit(id);
                if (film.Author != User.Identity.Name)
                {
                    throw new Exception("You can't edit this movie");
                }
                return View(film);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("edit/{id}")]
        public async Task<IActionResult> Edit(EditFilmViewModel model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }
            try
            {
                await _filmsService.Edit(model);
                return RedirectToAction("Index", "Home");
            }
            catch (Exception ex)
            {
                ModelState.AddModelError("", ex.Message);
                return View(model);
            }
        }

        [HttpGet]
        [Authorize]
        [Route("delete/{id}")]
        public async Task<IActionResult> Delete(int id)
        {
            try
            {
                var film = await _filmsService.GetForDelete(id);
                if (film.Author != User.Identity.Name)
                {
                    throw new Exception("You can't delete this movie");
                }
                return View(film);
            }
            catch
            {
                return RedirectToAction("Index", "Home");
            }
        }
        [HttpPost]
        [Authorize]
        [ValidateAntiForgeryToken]
        [Route("delete/{id}")]
        public async Task<IActionResult> Delete(DeleteFilmViewModel model)
        {
            try
            {  
                await _filmsService.Delete(model.Id);
                return RedirectToAction("Index", "Home");
            }
            catch
            {
                return RedirectToAction("Create");
            }
        }
    }
}

FilmsCatalog/Views/Films/Create.cshtml
@using FilmsCatalog.ViewModels
@model CreateFilmViewModel

<form asp-action="Create" asp-controller="Films" method="Post" 
enctype="multipart/form-data"> 
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Name">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description"></textarea>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Year"></label>
        <input type="number" min="1900" max="@DateTime.Now.AddYears(20).Year" class="form-control" asp-for="Year">
        <span class="text-danger" asp-validation-for="Year"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Director"></label>
        <input type="text" class="form-control" asp-for="Director">
        <span class="text-danger" asp-validation-for="Director"></span>
    </div> 
    <div class="mt-3">
        <label class="form-label" for="file">Постер</label>
        <input asp-for="File" type="file" id="file" class="form-control">
    </div>
    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>

FilmsCatalog/Views/Films/Delete.cshtml
@model FilmsCatalog.ViewModels.DeleteFilmViewModel

<h1>Вы действительно хотите удалить фильм?</h1>
<h2>@Model.Name</h2>

<form asp-action="Delete" asp-controller="Films" method="POST">
    <input type="hidden" asp-for="Id"/>
    <button class="btn btn-outline-danger" type="submit">Удалить</button>
    <a class="btn btn-outline-secondary" role="button" asp-action="Main">Отмена</a>
</form>

FilmsCatalog/Views/Films/Details.cshtml
@using FilmsCatalog.ViewModels
@model FilmViewModel

<h1>@Model.Name</h1>

<div class="row">
    <div class="col-8">
        
        <div class="list-group">
            <div class="list-group-item">
                @Model.Description
            </div>
            <div class="list-group-item">
                Год выпуска - @Model.Year
            </div>
            <div class="list-group-item">
                Режиссёр - @Model.Director
            </div>
            <p><b>Опубликовал:</b> @Model.User.FirstName @Model.User.LastName</p>
        </div>
        
        <div class="mt-3">
            <a asp-action="Index" asp-controller="Home" class="btn btn-outline-primary">Назад</a>
            @if (User.Identity.Name == @Model.User.UserName)
            {
                <a class="btn btn-outline-warning" asp-action="Edit" asp-controller="Films" asp-route-id="@Model.Id">Редактировать</a>
                <a class="btn btn-outline-danger" asp-action="Delete" asp-controller="Films" asp-route-id="@Model.Id">Удалить</a>
            }
        </div>
    </div>
    <div class="col-4">
        @if (!string.IsNullOrWhiteSpace(Model.FilePath))
        {
            <img src="@Model.FilePath" alt="@Model.Name" width="400"/>
        }
        else
        {
            <div class="alert alert-info">Постер не был загружен</div>
        }
    </div>
</div>

FilmsCatalog/Views/Films/Edit.cshtml
@model FilmsCatalog.ViewModels.EditFilmViewModel

<form asp-action="Edit" asp-controller="Films" method="Post" 
enctype="multipart/form-data"> 
    <div class="mb-3">
        <label asp-for="Name" class="form-label"></label>
        <input type="text" class="form-control" asp-for="Name">
        <span class="text-danger" asp-validation-for="Name"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Description"></label>
        <textarea class="form-control" asp-for="Description"></textarea>
        <span class="text-danger" asp-validation-for="Description"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Year"></label>
        <input type="number" min="1900" max="@DateTime.Now.AddYears(20).Year" class="form-control" asp-for="Year">
        <span class="text-danger" asp-validation-for="Year"></span>
    </div>
    <div class="mb-3">
        <label class="form-label" asp-for="Director"></label>
        <input type="text" class="form-control" asp-for="Director">
        <span class="text-danger" asp-validation-for="Director"></span>
    </div> 
    <div class="mt-3">
        <label class="form-label" for="file">Постер</label>
        <input asp-for="File" type="file" id="file" class="form-control">
    </div>
    <div class="text-danger" asp-validation-summary="All"></div>
    <button type="submit" class="btn btn-primary">Сохранить</button>
</form>